import type { Student, TPOFaculty, Company, Post, PendingItem, AppSettings, User, CalendarEvent } from "./types";

export const SETTINGS: AppSettings = {
  collegeName: "ADCET — AnnaSaheb Dange College of Engineering and Technology",
  academicYear: "2024-25",
  tpoEmail: "tpo@adcet.ac.in",
  emailDomainRestrict: true,
  allowedDomains: ["adcet.ac.in"],
  eligibility: { tenthMin: 60, twelfthMin: 60, cgpaMin: 6.0, combined: false },
  dreamPackageLpa: 8.0,
  superDreamPackageLpa: 15.0,
  maxBacklogsAllowed: 0,
  allowMultipleOffers: true,
  placementSeasonActive: true,
};

export const FACULTY: TPOFaculty[] = [
  {
    id: "f1",
    name: "Dr. Anita Deshpande",
    email: "anita.dean@adcet.ac.in",
    phone: "9876500001",
    department: "All",
    role: "tpo-admin",
  },
  {
    id: "f2",
    name: "Prof. Rajeev Khedkar",
    email: "rajeev.tpo@adcet.ac.in",
    phone: "9876500002",
    department: "All",
    role: "tpo-co-admin",
  },
  {
    id: "f3",
    name: "Prof. Smita Patil",
    email: "smita.cse@adcet.ac.in",
    phone: "9876500003",
    department: "Computer Engineering",
    role: "tpo-department",
  },
  {
    id: "f4",
    name: "Prof. Nilesh Kale",
    email: "nilesh.mod@adcet.ac.in",
    phone: "9876500004",
    department: "All",
    role: "moderator",
  },
];

export const COMPANIES: Company[] = [
  {
    id: "c1",
    name: "TCS",
    industry: "Information Technology / Software",
    website: "tcs.com",
    location: "Pune",
    ctcMin: 3.5,
    ctcMax: 7,
    addedOn: "2025-08-12",
    hrName: "Riya Shah",
    hrEmail: "hr@tcs.com",
    hrPhone: "9000000001",
    description: "Tata Consultancy Services — global IT services & consulting.",
  },
  {
    id: "c2",
    name: "Infosys",
    industry: "Information Technology / Software",
    website: "infosys.com",
    location: "Bengaluru",
    ctcMin: 3.6,
    ctcMax: 8,
    addedOn: "2025-08-20",
    hrName: "Amit Rao",
    hrEmail: "hr@infosys.com",
    hrPhone: "9000000002",
    description: "Digital services & consulting major.",
  },
  {
    id: "c3",
    name: "Cognizant",
    industry: "Information Technology / Software",
    website: "cognizant.com",
    location: "Chennai",
    ctcMin: 4,
    ctcMax: 9,
    addedOn: "2025-09-02",
    hrName: "Neha Verma",
    hrEmail: "hr@cognizant.com",
    hrPhone: "9000000003",
    description: "Professional services in IT & consulting.",
  },
  {
    id: "c4",
    name: "L&T",
    industry: "Civil & Infrastructure",
    website: "larsentoubro.com",
    location: "Mumbai",
    ctcMin: 4.5,
    ctcMax: 10,
    addedOn: "2025-09-18",
    hrName: "Karan Mehta",
    hrEmail: "hr@lnt.com",
    hrPhone: "9000000004",
    description: "Engineering, procurement & construction conglomerate.",
  },
];

export const STUDENTS: Student[] = [
  {
    id: "s1",
    userId: "u-student",
    name: "Aryan Patil",
    email: "aryan@adcet.ac.in",
    urn: "URN2021001",
    rollNumber: "CSE-21-01",
    department: "Computer Engineering",
    year: "Fourth",
    division: "A",
    cgpa: 8.4,
    backlogs: 0,
    activeBacklogs: false,
    admissionMonth: "July",
    admissionYear: "2021",
    passoutYear: "2025",
    tenth: {
      board: "Maharashtra Board",
      school: "New English School",
      year: "2019",
      percentage: 88,
    },
    twelfth: {
      board: "Maharashtra Board",
      school: "Vivekanand College",
      year: "2021",
      percentage: 81,
      stream: "Science",
      type: "12th",
    },
    gender: "Male",
    mobile: "9876543210",
    city: "Kolhapur",
    state: "Maharashtra",
    pin: "416001",
    category: "General",
    skills: ["React", "Node.js", "Python"],
    languages: ["English", "Marathi", "Hindi"],
    linkedin: "linkedin.com/in/aryan",
    github: "github.com/aryan",
    status: "verified",
    placementStatus: "Placed",
    placedCompany: "TCS",
    packageLpa: 6.5,
  },
  {
    id: "s2",
    userId: "u2",
    name: "Sneha Joshi",
    email: "sneha@adcet.ac.in",
    urn: "URN2021002",
    rollNumber: "CSE-21-02",
    department: "Computer Engineering",
    year: "Fourth",
    division: "A",
    cgpa: 9.1,
    backlogs: 0,
    activeBacklogs: false,
    admissionMonth: "July",
    admissionYear: "2021",
    passoutYear: "2025",
    tenth: { board: "CBSE", school: "DAV Public School", year: "2019", percentage: 92 },
    twelfth: {
      board: "CBSE",
      school: "DAV Public School",
      year: "2021",
      percentage: 89,
      stream: "Science",
      type: "12th",
    },
    gender: "Female",
    mobile: "9876543211",
    city: "Sangli",
    state: "Maharashtra",
    pin: "416416",
    category: "General",
    skills: ["Java", "Spring", "SQL"],
    languages: ["English", "Hindi"],
    status: "verified",
    placementStatus: "Placed",
    placedCompany: "Infosys",
    packageLpa: 7.2,
  },
  {
    id: "s3",
    userId: "u3",
    name: "Rahul Kamble",
    email: "rahul@adcet.ac.in",
    urn: "URN2021003",
    rollNumber: "MEC-21-08",
    department: "Mechanical",
    year: "Fourth",
    division: "B",
    cgpa: 6.8,
    backlogs: 1,
    activeBacklogs: false,
    admissionMonth: "July",
    admissionYear: "2021",
    passoutYear: "2025",
    tenth: { board: "Maharashtra Board", school: "Shahu Vidyalaya", year: "2019", percentage: 72 },
    twelfth: {
      board: "MSBTE",
      school: "Govt. Polytechnic",
      year: "2021",
      percentage: 74,
      stream: "Mechanical",
      type: "Diploma",
    },
    gender: "Male",
    mobile: "9876543212",
    city: "Ichalkaranji",
    state: "Maharashtra",
    pin: "416115",
    category: "OBC",
    skills: ["AutoCAD", "SolidWorks"],
    languages: ["Marathi", "Hindi"],
    status: "verified",
    placementStatus: "In Process",
  },
  {
    id: "s4",
    userId: "u4",
    name: "Priya More",
    email: "priya@adcet.ac.in",
    urn: "URN2021004",
    rollNumber: "ENT-21-15",
    department: "Electronics",
    year: "Third",
    division: "A",
    cgpa: 7.9,
    backlogs: 0,
    activeBacklogs: false,
    admissionMonth: "July",
    admissionYear: "2022",
    passoutYear: "2026",
    tenth: { board: "Maharashtra Board", school: "St. Xavier's", year: "2020", percentage: 84 },
    twelfth: {
      board: "Maharashtra Board",
      school: "St. Xavier's",
      year: "2022",
      percentage: 79,
      stream: "Science",
      type: "12th",
    },
    gender: "Female",
    mobile: "9876543213",
    city: "Pune",
    state: "Maharashtra",
    pin: "411001",
    category: "General",
    skills: ["VLSI", "Embedded C"],
    languages: ["English", "Marathi"],
    status: "pending",
    placementStatus: "Not Placed",
  },
  {
    id: "s5",
    userId: "u5",
    name: "Omkar Shinde",
    email: "omkar@adcet.ac.in",
    urn: "URN2022014",
    rollNumber: "CIV-22-03",
    department: "Civil",
    year: "Third",
    division: "C",
    cgpa: 5.4,
    backlogs: 3,
    activeBacklogs: true,
    admissionMonth: "July",
    admissionYear: "2022",
    passoutYear: "2026",
    tenth: { board: "Maharashtra Board", school: "Modern High", year: "2020", percentage: 58 },
    twelfth: {
      board: "Maharashtra Board",
      school: "Modern Jr. College",
      year: "2022",
      percentage: 62,
      stream: "Science",
      type: "12th",
    },
    gender: "Male",
    mobile: "9876543214",
    city: "Satara",
    state: "Maharashtra",
    pin: "415001",
    category: "SC",
    skills: ["AutoCAD", "Surveying"],
    languages: ["Marathi"],
    status: "draft",
    placementStatus: "Not Placed",
  },
];

export const POSTS: Post[] = [
  {
    id: "p1",
    type: "Notice",
    title: "TCS NQT 2025 — Eligibility & Schedule",
    body: "All eligible students from CSE, IT, ENTC must register on the TCS portal by Friday. Test window opens next Monday across 3 slots. Please ensure your TCS NQT profile is complete and verified.",
    authorName: "Prof. Rajeev Khedkar",
    authorRole: "TPO Co-Admin",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    likes: 24,
    comments: [
      {
        id: "c1",
        author: "Aryan Patil",
        role: "Student",
        text: "Registered. Thanks!",
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "p2",
    type: "Post",
    title: "Pre-placement talk — Infosys",
    body: "Infosys is conducting a PPT on 28th May at Auditorium-1, 11:00 AM. Open to all final-year students. Snacks will be provided. Don't miss the Q&A with hiring managers!",
    authorName: "Prof. Smita Patil",
    authorRole: "Dept. TPO",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    likes: 12,
    comments: [],
  },
  {
    id: "p3",
    type: "Poll",
    title: "Reminder: Submit your verified profile",
    body: "Profiles in 'draft' state won't be considered for upcoming drives. Please complete and submit for verification at the earliest.",
    authorName: "Dr. Anita Deshpande",
    authorRole: "TPO Admin",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    likes: 7,
    comments: [],
    pollOptions: [
      { id: "o1", text: "Ready for placements", votes: 45 },
      { id: "o2", text: "Need more time", votes: 12 },
    ],
  },
];

export const PENDING: PendingItem[] = [
  {
    id: "pv1",
    kind: "new",
    studentId: "s4",
    studentName: "Priya More",
    urn: "URN2021004",
    department: "Electronics",
    submittedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "pv2",
    kind: "update",
    studentId: "s1",
    studentName: "Aryan Patil",
    urn: "URN2021001",
    department: "Computer Engineering",
    submittedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    changes: [
      { field: "Mobile", before: "9876543210", after: "9123456780" },
      { field: "City", before: "Kolhapur", after: "Pune" },
      { field: "CGPA", before: "8.2", after: "8.4" },
    ],
  },
];

export const DEMO_USERS: (User & { password: string })[] = [
  {
    id: "u-student",
    name: "Aryan Patil",
    email: "student@adcet.ac.in",
    role: "student",
    password: "password",
  },
  {
    id: "u-admin",
    name: "Dr. Anita Deshpande",
    email: "admin@adcet.ac.in",
    role: "tpo-admin",
    password: "password",
  },
  {
    id: "u-dept",
    name: "Prof. Smita Patil",
    email: "dept@adcet.ac.in",
    role: "tpo-department",
    department: "Computer Engineering",
    password: "password",
  },
];

export const DEPARTMENTS = [
  "Computer Engineering",
  "Mechanical",
  "Civil",
  "Electronics",
  "Information Technology",
  "Electrical",
];

const today = new Date();
const fmt = (offset: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offset);
  return d.toISOString().split("T")[0];
};

export const EVENTS: CalendarEvent[] = [
  {
    id: "ev1",
    title: "TCS NQT Campus Drive",
    date: fmt(2),
    time: "09:00 AM – 05:00 PM",
    location: "Main Auditorium, ADCET",
    isOnline: false,
    type: "Placement",
    description: "TCS Ninja & Digital campus recruitment. Bring offer letter printout, 2 copies of resume, and all original mark sheets.",
    targetAudience: "Final Year – CSE, IT, ENTC",
    createdBy: "Prof. Rajeev Khedkar",
    createdByRole: "TPO Co-Admin",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
  {
    id: "ev2",
    title: "Resume Building Workshop",
    date: fmt(5),
    time: "02:00 PM – 04:00 PM",
    location: "Online – Google Meet",
    isOnline: true,
    type: "Workshop",
    description: "Learn how to craft an ATS-friendly resume. Guest speaker from LinkedIn India.",
    targetAudience: "All Students",
    createdBy: "Dr. Anita Deshpande",
    createdByRole: "TPO Admin",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
  {
    id: "ev3",
    title: "Mock Interview Session",
    date: fmt(8),
    time: "10:00 AM – 01:00 PM",
    location: "Seminar Hall 2, Block B",
    isOnline: false,
    type: "Training",
    description: "HR & Technical mock interviews conducted by industry professionals. Slots of 20 minutes each.",
    targetAudience: "Final Year – All Branches",
    createdBy: "Prof. Smita Patil",
    createdByRole: "Dept. TPO – CSE",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "ev4",
    title: "Aptitude Test Series – Round 3",
    date: fmt(12),
    time: "04:00 PM – 05:30 PM",
    location: "Online – HackerEarth",
    isOnline: true,
    type: "Assessment",
    description: "Third round of the weekly aptitude series. Topics: Data Interpretation, Logical Reasoning.",
    targetAudience: "All Students",
    createdBy: "Prof. Nilesh Kale",
    createdByRole: "Moderator",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "ev5",
    title: "Infosys Pre-Placement Talk",
    date: fmt(15),
    time: "11:00 AM – 12:30 PM",
    location: "Auditorium-1, ADCET",
    isOnline: false,
    type: "Placement",
    description: "Infosys hiring managers will present the role, growth path, and compensation structure. Q&A session included.",
    targetAudience: "Final Year – All Branches",
    createdBy: "Prof. Smita Patil",
    createdByRole: "Dept. TPO – CSE",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
  },
];
