/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TpoRouteImport } from './routes/tpo'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TpoStudentsRouteImport } from './routes/tpo.students'
import { Route as TpoSettingsRouteImport } from './routes/tpo.settings'
import { Route as TpoFeedRouteImport } from './routes/tpo.feed'
import { Route as TpoFacultyRouteImport } from './routes/tpo.faculty'
import { Route as TpoDashboardRouteImport } from './routes/tpo.dashboard'
import { Route as TpoCompaniesRouteImport } from './routes/tpo.companies'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentHomeRouteImport } from './routes/student.home'

const TpoRoute = TpoRouteImport.update({
  id: '/tpo',
  path: '/tpo',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TpoStudentsRoute = TpoStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TpoRoute,
} as any)
const TpoSettingsRoute = TpoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TpoRoute,
} as any)
const TpoFeedRoute = TpoFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => TpoRoute,
} as any)
const TpoFacultyRoute = TpoFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => TpoRoute,
} as any)
const TpoDashboardRoute = TpoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TpoRoute,
} as any)
const TpoCompaniesRoute = TpoCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => TpoRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHomeRoute = StudentHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/tpo': typeof TpoRouteWithChildren
  '/student/home': typeof StudentHomeRoute
  '/student/profile': typeof StudentProfileRoute
  '/tpo/companies': typeof TpoCompaniesRoute
  '/tpo/dashboard': typeof TpoDashboardRoute
  '/tpo/faculty': typeof TpoFacultyRoute
  '/tpo/feed': typeof TpoFeedRoute
  '/tpo/settings': typeof TpoSettingsRoute
  '/tpo/students': typeof TpoStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/tpo': typeof TpoRouteWithChildren
  '/student/home': typeof StudentHomeRoute
  '/student/profile': typeof StudentProfileRoute
  '/tpo/companies': typeof TpoCompaniesRoute
  '/tpo/dashboard': typeof TpoDashboardRoute
  '/tpo/faculty': typeof TpoFacultyRoute
  '/tpo/feed': typeof TpoFeedRoute
  '/tpo/settings': typeof TpoSettingsRoute
  '/tpo/students': typeof TpoStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/tpo': typeof TpoRouteWithChildren
  '/student/home': typeof StudentHomeRoute
  '/student/profile': typeof StudentProfileRoute
  '/tpo/companies': typeof TpoCompaniesRoute
  '/tpo/dashboard': typeof TpoDashboardRoute
  '/tpo/faculty': typeof TpoFacultyRoute
  '/tpo/feed': typeof TpoFeedRoute
  '/tpo/settings': typeof TpoSettingsRoute
  '/tpo/students': typeof TpoStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/student'
    | '/tpo'
    | '/student/home'
    | '/student/profile'
    | '/tpo/companies'
    | '/tpo/dashboard'
    | '/tpo/faculty'
    | '/tpo/feed'
    | '/tpo/settings'
    | '/tpo/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/student'
    | '/tpo'
    | '/student/home'
    | '/student/profile'
    | '/tpo/companies'
    | '/tpo/dashboard'
    | '/tpo/faculty'
    | '/tpo/feed'
    | '/tpo/settings'
    | '/tpo/students'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/student'
    | '/tpo'
    | '/student/home'
    | '/student/profile'
    | '/tpo/companies'
    | '/tpo/dashboard'
    | '/tpo/faculty'
    | '/tpo/feed'
    | '/tpo/settings'
    | '/tpo/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  TpoRoute: typeof TpoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tpo': {
      id: '/tpo'
      path: '/tpo'
      fullPath: '/tpo'
      preLoaderRoute: typeof TpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpo/students': {
      id: '/tpo/students'
      path: '/students'
      fullPath: '/tpo/students'
      preLoaderRoute: typeof TpoStudentsRouteImport
      parentRoute: typeof TpoRoute
    }
    '/tpo/settings': {
      id: '/tpo/settings'
      path: '/settings'
      fullPath: '/tpo/settings'
      preLoaderRoute: typeof TpoSettingsRouteImport
      parentRoute: typeof TpoRoute
    }
    '/tpo/feed': {
      id: '/tpo/feed'
      path: '/feed'
      fullPath: '/tpo/feed'
      preLoaderRoute: typeof TpoFeedRouteImport
      parentRoute: typeof TpoRoute
    }
    '/tpo/faculty': {
      id: '/tpo/faculty'
      path: '/faculty'
      fullPath: '/tpo/faculty'
      preLoaderRoute: typeof TpoFacultyRouteImport
      parentRoute: typeof TpoRoute
    }
    '/tpo/dashboard': {
      id: '/tpo/dashboard'
      path: '/dashboard'
      fullPath: '/tpo/dashboard'
      preLoaderRoute: typeof TpoDashboardRouteImport
      parentRoute: typeof TpoRoute
    }
    '/tpo/companies': {
      id: '/tpo/companies'
      path: '/companies'
      fullPath: '/tpo/companies'
      preLoaderRoute: typeof TpoCompaniesRouteImport
      parentRoute: typeof TpoRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/home': {
      id: '/student/home'
      path: '/home'
      fullPath: '/student/home'
      preLoaderRoute: typeof StudentHomeRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentHomeRoute: typeof StudentHomeRoute
  StudentProfileRoute: typeof StudentProfileRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentHomeRoute: StudentHomeRoute,
  StudentProfileRoute: StudentProfileRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TpoRouteChildren {
  TpoCompaniesRoute: typeof TpoCompaniesRoute
  TpoDashboardRoute: typeof TpoDashboardRoute
  TpoFacultyRoute: typeof TpoFacultyRoute
  TpoFeedRoute: typeof TpoFeedRoute
  TpoSettingsRoute: typeof TpoSettingsRoute
  TpoStudentsRoute: typeof TpoStudentsRoute
}

const TpoRouteChildren: TpoRouteChildren = {
  TpoCompaniesRoute: TpoCompaniesRoute,
  TpoDashboardRoute: TpoDashboardRoute,
  TpoFacultyRoute: TpoFacultyRoute,
  TpoFeedRoute: TpoFeedRoute,
  TpoSettingsRoute: TpoSettingsRoute,
  TpoStudentsRoute: TpoStudentsRoute,
}

const TpoRouteWithChildren = TpoRoute._addFileChildren(TpoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  TpoRoute: TpoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
